name: Deploy IAM Service

# run-name is not supported yet with our github
#run-name: Deploying ${{ inputs.service_name }} (${{ inputs.service_version }}) to ${{ inputs.deploy_environment }}

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: 'IAM Service Name'
        required: true
        type: choice
        options:
          - authentication
          - gateway
          - identity
      service_version:
        description: 'IAM Service Version'
        required: true
        type: string
      deploy_environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - stage
          - production

jobs:
  deploy-helm-chart:
    runs-on: default
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Dispatch deploy ${{ inputs.service_name }} v${{ inputs.service_version }} to ${{ inputs.deploy_environment }}
        id: deploy-service
        uses: ./.github/actions/deploy-service
        with:
          service_name: ${{ inputs.service_name }}
          service_version: ${{ inputs.service_version }}
          deploy_environment: ${{ inputs.deploy_environment }}
      - name: Tag branch w/ release version
        uses: actions/github-script@v6
        env:
          IAM_BUILD_VERSION: ${{ inputs.service_version }}
        with:
          script: |
            const { IAM_BUILD_VERSION } = process.env;
            try {
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${IAM_BUILD_VERSION}`,
                sha: context.sha
              });
            } catch (e) {
              console.log(`failed to create version tag with error: ${e.name} ${e.message}`);
            }